---
apiVersion: v1
kind: Service
metadata:
  name: rstudio
  labels:
    app: rstudio
spec:
  ports:
    - port: 8787
      name: rstudio
      protocol: TCP
      targetPort: 8787
  selector:
    app: rstudio
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: rstudio
  labels:
    app: rstudio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rstudio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rstudio
    spec:
      containers:
      - image: quay.agilesof.com/mbach/rstudio:rhel7-latest
        imagePullPolicy: Always
        name: rstudio-rhel7
        ports:
        - containerPort: 8787
          name: rstudio
